/** Curated story presets — interesting construct × form × filter combinations. */

import { DEFAULT_SPEC, type PosterSpec, type StatMarkId } from "./types";
import { specToSearchParams } from "./specUrl";

export interface StoryPreset {
  id: string;
  /** Short concept title shown on the card */
  concept: string;
  /** One-line hook — what this cut reveals */
  hook: string;
  /** Display chips (form, era, filter idea) */
  tags: string[];
  /** Partial spec merged onto DEFAULT_SPEC when opening the atelier */
  spec: Partial<PosterSpec> & Pick<PosterSpec, "activeConstruct" | "heroForm">;
}

export interface GalleryCollection {
  id: string;
  label: string;
  /** Short blurb under the tab strip */
  blurb: string;
  stories: StoryPreset[];
}

const marks = (...ids: StatMarkId[]): StatMarkId[] => ids;

/** Visually loud cuts — form, density, and palette first. */
const LOOK_COOL: StoryPreset[] = [
  {
    id: "cool-scream-dense",
    concept: "Scream-queen knot",
    hook: "Winstead, Thoms, Rodriguez — horror co-appearance as a dense chord.",
    tags: ["Chord", "Dense", "Horror"],
    spec: {
      activeConstruct: "scream_queen",
      heroForm: "chord",
      topN: 80,
      minWeight: 4,
      colorMode: "gender",
      labelMode: "none",
      palette: "loom",
      sortBy: "strength",
      statMarks: marks("densest_pair", "top5_degree", "featured_path"),
    },
  },
  {
    id: "cool-repertory-ring",
    concept: "Repertory ring",
    hook: "Tight troupes (≥3 shared titles) — collaboration as a hard circle.",
    tags: ["Chord", "Repertory", "Dense"],
    spec: {
      activeConstruct: "repertory",
      heroForm: "chord",
      topN: 72,
      minWeight: 4,
      colorMode: "degree",
      labelMode: "none",
      palette: "ink",
      sortBy: "strength",
      statMarks: marks("densest_pair", "loyalty_pair", "top5_degree"),
    },
  },
  {
    id: "cool-dubbing-dusk",
    concept: "Dubbing dusk bundle",
    hook: "Voice careers edge-bundled in dusk — soft loom, many characters.",
    tags: ["Bundle", "Dusk", "Voice"],
    spec: {
      activeConstruct: "dubbing",
      heroForm: "bundle",
      topN: 140,
      minWeight: 2,
      colorMode: "degree",
      labelMode: "none",
      palette: "dusk",
      sortBy: "strength",
    },
  },
  {
    id: "cool-franchise-fan",
    concept: "Franchise fan-out",
    hook: "People hopping three or more IPs — a wide dusk bundle.",
    tags: ["Bundle", "Franchise", "Dusk"],
    spec: {
      activeConstruct: "franchise_nomads",
      heroForm: "bundle",
      topN: 100,
      minWeight: 3,
      colorMode: "degree",
      labelMode: "none",
      palette: "dusk",
      sortBy: "strength",
      statMarks: marks("community_cuts", "top5_degree"),
    },
  },
  {
    id: "cool-genre-ink",
    concept: "Ink genre bridges",
    hook: "Near-monochrome bundling — multi-genre connectors without loud color.",
    tags: ["Bundle", "Ink", "Bridges"],
    spec: {
      activeConstruct: "genre_bridge",
      heroForm: "bundle",
      topN: 110,
      minWeight: 3,
      minTitles: 5,
      colorMode: "degree",
      labelMode: "none",
      palette: "ink",
      sortBy: "title_count",
    },
  },
  {
    id: "cool-long-flip",
    concept: "Longevity, flipped",
    hook: "Half-century careers with axes swapped — years read as strata.",
    tags: ["Timeline", "Flip", "Longevity"],
    spec: {
      activeConstruct: "long_careers",
      heroForm: "timeline",
      topN: 64,
      minWeight: 2,
      timelineFlip: true,
      sortBy: "year_peak",
      minTitles: 6,
      labelMode: "hubs",
      palette: "loom",
      statMarks: marks("median_peak", "span_outliers", "gap_spikes"),
    },
  },
  {
    id: "cool-silent-lanes",
    concept: "Silent → sound skyline",
    hook: "Careers that straddled 1927 — lanes across the talkie break.",
    tags: ["Timeline", "Silent era"],
    spec: {
      activeConstruct: "silent_sound",
      heroForm: "timeline",
      topN: 70,
      minWeight: 1,
      sortBy: "year_peak",
      labelMode: "none",
      palette: "ink",
      statMarks: marks("median_peak", "mode_decade", "gap_spikes"),
    },
  },
  {
    id: "cool-blockbuster-scatter",
    concept: "Blockbuster cloud",
    hook: "Strength × prominence for top-decile-vote careers — Jackson, Downey, Johansson.",
    tags: ["Scatter", "Blockbuster"],
    spec: {
      activeConstruct: "blockbuster",
      heroForm: "scatter",
      topN: 160,
      minWeight: 2,
      sortBy: "prominence",
      colorMode: "degree",
      palette: "loom",
    },
  },
  {
    id: "cool-comedy-horror-ring",
    concept: "Crossover ring",
    hook: "Comedy × horror as a tight chord — laughs and screams sharing the circle.",
    tags: ["Chord", "Crossover"],
    spec: {
      activeConstruct: "comedy_horror",
      heroForm: "chord",
      topN: 90,
      minWeight: 4,
      colorMode: "degree",
      labelMode: "hubs",
      palette: "dusk",
      sortBy: "strength",
      statMarks: marks("densest_pair", "top5_degree"),
    },
  },
  {
    id: "cool-cartoons-wide",
    concept: "Cartoon skyline",
    hook: "Wide timeline of animation voice careers — lanes stacked like a skyline.",
    tags: ["Timeline", "Animation"],
    spec: {
      activeConstruct: "voice_cartoons",
      heroForm: "timeline",
      topN: 120,
      minWeight: 2,
      minTitles: 3,
      sortBy: "year_peak",
      labelMode: "none",
      palette: "dusk",
      statMarks: marks("median_peak", "mode_decade", "top5_degree"),
    },
  },
  {
    id: "cool-bechdel-bundle",
    concept: "Bechdel as fabric",
    hook: "Pass-film collaborations edge-bundled — collaboration as cloth.",
    tags: ["Bundle", "Bechdel"],
    spec: {
      activeConstruct: "bechdel",
      heroForm: "bundle",
      topN: 100,
      minWeight: 3,
      colorMode: "gender",
      labelMode: "none",
      palette: "loom",
      sortBy: "strength",
    },
  },
  {
    id: "cool-men-horror-tight",
    concept: "Horror men — tight weave",
    hook: "Lee, Cage, Oldman — fewer nodes, higher weight, ink palette.",
    tags: ["Chord", "min wt 5"],
    spec: {
      activeConstruct: "men_horror",
      heroForm: "chord",
      topN: 56,
      minWeight: 5,
      genderFilter: "male",
      colorMode: "degree",
      labelMode: "hubs",
      palette: "ink",
      sortBy: "strength",
      statMarks: marks("densest_pair", "featured_path"),
    },
  },
];

/** Horror-family constructs and era cuts. */
const HORROR: StoryPreset[] = [
  {
    id: "horror-scream-classic",
    concept: "The scream-queen web",
    hook: "Actresses recurring across horror — co-appearance as the weave.",
    tags: ["Scream queen", "Chord"],
    spec: {
      activeConstruct: "scream_queen",
      heroForm: "chord",
      topN: 100,
      minWeight: 3,
      colorMode: "gender",
      sortBy: "strength",
      palette: "loom",
      labelMode: "hubs",
      statMarks: marks("densest_pair", "featured_path", "top5_degree"),
    },
  },
  {
    id: "horror-scream-timeline",
    concept: "Scream queens over time",
    hook: "Career lanes for the same horror co-appearance cast.",
    tags: ["Scream queen", "Timeline"],
    spec: {
      activeConstruct: "scream_queen",
      heroForm: "timeline",
      topN: 90,
      minWeight: 2,
      sortBy: "year_peak",
      colorMode: "gender",
      palette: "loom",
      statMarks: marks("gap_spikes", "median_peak", "mode_decade"),
    },
  },
  {
    id: "horror-scream-modern",
    concept: "After 2000",
    hook: "Scream-queen web limited to careers touching the 21st century.",
    tags: ["2000–", "Timeline"],
    spec: {
      activeConstruct: "scream_queen",
      heroForm: "timeline",
      topN: 100,
      minWeight: 2,
      yearFrom: 2000,
      yearTo: 2030,
      edgeYearFilter: true,
      colorMode: "gender",
      sortBy: "year_peak",
      palette: "dusk",
    },
  },
  {
    id: "horror-bloodlines",
    concept: "Horror royalty",
    hook: "Men + women with ≥4 horror titles — Jackson, Cox, Lee in one court.",
    tags: ["Bloodlines", "Chord"],
    spec: {
      activeConstruct: "horror_bloodlines",
      heroForm: "chord",
      topN: 90,
      minWeight: 3,
      colorMode: "gender",
      sortBy: "strength",
      palette: "ink",
      labelMode: "hubs",
      statMarks: marks("densest_pair", "top5_degree", "assortativity"),
    },
  },
  {
    id: "horror-women-full",
    concept: "Women in horror",
    hook: "Female-coded cast — gender → prominence → title profile.",
    tags: ["Women", "Chord"],
    spec: {
      activeConstruct: "women_horror",
      heroForm: "chord",
      topN: 100,
      minWeight: 2,
      colorMode: "degree",
      sortBy: "prominence",
      palette: "dusk",
      labelMode: "hubs",
    },
  },
  {
    id: "horror-women-boom",
    concept: "Women · boom decades",
    hook: "Careers overlapping 1975–2005 — when horror’s female cast thickened.",
    tags: ["1975–2005", "Timeline"],
    spec: {
      activeConstruct: "women_horror",
      heroForm: "timeline",
      topN: 100,
      minWeight: 2,
      yearFrom: 1975,
      yearTo: 2005,
      genderFilter: "female",
      sortBy: "year_peak",
      colorMode: "gender",
      palette: "dusk",
      statMarks: marks("median_peak", "gap_spikes"),
    },
  },
  {
    id: "horror-women-timeline",
    concept: "Women · career lanes",
    hook: "Horror actresses as a timeline — who overlapped which decades.",
    tags: ["Women", "Timeline"],
    spec: {
      activeConstruct: "women_horror",
      heroForm: "timeline",
      topN: 100,
      minWeight: 2,
      sortBy: "year_peak",
      colorMode: "degree",
      palette: "loom",
    },
  },
  {
    id: "horror-men-full",
    concept: "Men in horror",
    hook: "Male-coded horror cast — hubs by co-appearance strength.",
    tags: ["Men", "Chord"],
    spec: {
      activeConstruct: "men_horror",
      heroForm: "chord",
      topN: 100,
      minWeight: 2,
      genderFilter: "male",
      colorMode: "degree",
      sortBy: "strength",
      palette: "ink",
      labelMode: "hubs",
    },
  },
  {
    id: "horror-men-tight",
    concept: "Men · tight clique",
    hook: "Top 70, min weight 4 — only the densest horror-male links.",
    tags: ["Men", "Dense"],
    spec: {
      activeConstruct: "men_horror",
      heroForm: "chord",
      topN: 70,
      minWeight: 4,
      genderFilter: "male",
      colorMode: "degree",
      labelMode: "hubs",
      palette: "ink",
      sortBy: "strength",
      statMarks: marks("densest_pair", "loyalty_pair"),
    },
  },
  {
    id: "horror-men-bundle",
    concept: "Men · edge bundle",
    hook: "Same population as a hierarchical bundle — clusters without the circle.",
    tags: ["Men", "Bundle"],
    spec: {
      activeConstruct: "men_horror",
      heroForm: "bundle",
      topN: 110,
      minWeight: 2,
      genderFilter: "male",
      colorMode: "degree",
      labelMode: "hubs",
      palette: "dusk",
    },
  },
  {
    id: "horror-crossover",
    concept: "Comedy × horror",
    hook: "Careers that live in both lanes — crossover co-appearance.",
    tags: ["Crossover", "Chord"],
    spec: {
      activeConstruct: "comedy_horror",
      heroForm: "chord",
      topN: 100,
      minWeight: 3,
      colorMode: "degree",
      sortBy: "strength",
      palette: "loom",
      labelMode: "hubs",
    },
  },
  {
    id: "horror-crossover-time",
    concept: "Crossover careers",
    hook: "Comedy–horror people as career lanes across decades.",
    tags: ["Crossover", "Timeline"],
    spec: {
      activeConstruct: "comedy_horror",
      heroForm: "timeline",
      topN: 90,
      minWeight: 2,
      sortBy: "year_peak",
      minTitles: 3,
      palette: "dusk",
      statMarks: marks("genre_drift", "median_peak"),
    },
  },
  {
    id: "horror-scatter",
    concept: "Horror strength cloud",
    hook: "Bloodlines cast as strength × prominence — who is dense vs famous.",
    tags: ["Scatter", "Horror"],
    spec: {
      activeConstruct: "horror_bloodlines",
      heroForm: "scatter",
      topN: 160,
      minWeight: 2,
      sortBy: "prominence",
      palette: "ink",
    },
  },
];

/** Voice acting, cartoons, dubbing multiverse. */
const VOICE: StoryPreset[] = [
  {
    id: "voice-cartoons-lanes",
    concept: "Cartoon career lanes",
    hook: "Hanazawa, Sakurai, Nakamura — who overlapped across animation decades.",
    tags: ["Cartoons", "Timeline"],
    spec: {
      activeConstruct: "voice_cartoons",
      heroForm: "timeline",
      topN: 110,
      minWeight: 2,
      minTitles: 3,
      sortBy: "year_peak",
      labelMode: "hubs",
      palette: "dusk",
      statMarks: marks("median_peak", "mode_decade", "top5_degree"),
    },
  },
  {
    id: "voice-cartoons-chord",
    concept: "Cartoon co-appearance",
    hook: "Shared animation titles as a chord — the voice-room clique.",
    tags: ["Cartoons", "Chord"],
    spec: {
      activeConstruct: "voice_cartoons",
      heroForm: "chord",
      topN: 100,
      minWeight: 3,
      colorMode: "degree",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "loom",
      statMarks: marks("densest_pair", "community_cuts"),
    },
  },
  {
    id: "voice-cartoons-bundle",
    concept: "Cartoon bundles",
    hook: "Hierarchical edge bundling on animation voice credits.",
    tags: ["Cartoons", "Bundle"],
    spec: {
      activeConstruct: "voice_cartoons",
      heroForm: "bundle",
      topN: 120,
      minWeight: 2,
      colorMode: "degree",
      labelMode: "hubs",
      palette: "dusk",
    },
  },
  {
    id: "voice-cartoons-women",
    concept: "Women voicing cartoons",
    hook: "Female-coded voice careers in animation.",
    tags: ["Female", "Timeline"],
    spec: {
      activeConstruct: "voice_cartoons",
      heroForm: "timeline",
      topN: 90,
      minWeight: 2,
      genderFilter: "female",
      colorMode: "gender",
      sortBy: "strength",
      minTitles: 2,
      palette: "loom",
    },
  },
  {
    id: "voice-cartoons-men",
    concept: "Men voicing cartoons",
    hook: "Male-coded animation voice lanes — strength-sorted hubs.",
    tags: ["Male", "Timeline"],
    spec: {
      activeConstruct: "voice_cartoons",
      heroForm: "timeline",
      topN: 90,
      minWeight: 2,
      genderFilter: "male",
      colorMode: "gender",
      sortBy: "strength",
      minTitles: 2,
      palette: "ink",
    },
  },
  {
    id: "voice-cartoons-classic",
    concept: "Classic-to-cable overlap",
    hook: "Animation careers touching 1960–1990 — before the streaming boom.",
    tags: ["1960–1990", "Timeline"],
    spec: {
      activeConstruct: "voice_cartoons",
      heroForm: "timeline",
      topN: 100,
      minWeight: 2,
      yearFrom: 1960,
      yearTo: 1990,
      sortBy: "year_peak",
      colorMode: "degree",
      palette: "ink",
      labelMode: "hubs",
      statMarks: marks("median_peak", "mode_decade"),
    },
  },
  {
    id: "voice-dubbing-fanout",
    concept: "Dubbing multiverse",
    hook: "Rial, Ruff, Haberkorn — character-heavy voice careers as a bundle.",
    tags: ["Dubbing", "Bundle"],
    spec: {
      activeConstruct: "dubbing",
      heroForm: "bundle",
      topN: 130,
      minWeight: 2,
      colorMode: "degree",
      labelMode: "hubs",
      palette: "dusk",
      sortBy: "strength",
    },
  },
  {
    id: "voice-dubbing-chord",
    concept: "Dubbing as chord",
    hook: "Same multiverse on a circle — who shares character-heavy careers.",
    tags: ["Dubbing", "Chord"],
    spec: {
      activeConstruct: "dubbing",
      heroForm: "chord",
      topN: 100,
      minWeight: 2,
      colorMode: "degree",
      labelMode: "hubs",
      palette: "loom",
      sortBy: "strength",
    },
  },
  {
    id: "voice-dubbing-time",
    concept: "Dubbing careers",
    hook: "Character-heavy voice careers stretched across years.",
    tags: ["Dubbing", "Timeline"],
    spec: {
      activeConstruct: "dubbing",
      heroForm: "timeline",
      topN: 90,
      minWeight: 2,
      sortBy: "year_peak",
      minTitles: 3,
      palette: "dusk",
    },
  },
  {
    id: "voice-dubbing-women",
    concept: "Women in the multiverse",
    hook: "Female-coded dubbing / many-character voice careers.",
    tags: ["Female", "Bundle"],
    spec: {
      activeConstruct: "dubbing",
      heroForm: "bundle",
      topN: 90,
      minWeight: 2,
      genderFilter: "female",
      colorMode: "gender",
      labelMode: "hubs",
      palette: "loom",
    },
  },
  {
    id: "voice-cartoons-modern",
    concept: "Cartoons since 1990",
    hook: "Animation voice web for the cable / streaming era.",
    tags: ["1990–", "Timeline"],
    spec: {
      activeConstruct: "voice_cartoons",
      heroForm: "timeline",
      topN: 110,
      minWeight: 2,
      yearFrom: 1990,
      yearTo: 2030,
      edgeYearFilter: true,
      sortBy: "year_peak",
      minTitles: 2,
      palette: "dusk",
    },
  },
  {
    id: "voice-face-lanes",
    concept: "Voice ↔ face",
    hook: "People with both animation voice and live-action movie careers.",
    tags: ["Voice", "Face", "Timeline"],
    spec: {
      activeConstruct: "voice_face",
      heroForm: "timeline",
      topN: 100,
      minWeight: 2,
      sortBy: "year_peak",
      colorMode: "gender",
      palette: "loom",
      labelMode: "hubs",
      statMarks: marks("genre_drift", "median_peak"),
    },
  },
  {
    id: "voice-prolific",
    concept: "Prolific cartoon voices",
    hook: "Min 5 titles — busier animation careers only.",
    tags: ["min titles 5", "Chord"],
    spec: {
      activeConstruct: "voice_cartoons",
      heroForm: "chord",
      topN: 90,
      minWeight: 3,
      minTitles: 5,
      sortBy: "title_count",
      colorMode: "degree",
      palette: "ink",
      labelMode: "hubs",
    },
  },
];

/** Careers, bridges, Bechdel, one-role concentration. */
const CAREERS: StoryPreset[] = [
  {
    id: "careers-long",
    concept: "Long careers",
    hook: "Chopra, Irani, Lee — 35+ year credited spans as lanes.",
    tags: ["Longevity", "Timeline"],
    spec: {
      activeConstruct: "long_careers",
      heroForm: "timeline",
      topN: 90,
      minWeight: 2,
      sortBy: "year_peak",
      minTitles: 4,
      labelMode: "hubs",
      palette: "loom",
      statMarks: marks("span_outliers", "median_peak", "gap_spikes"),
    },
  },
  {
    id: "careers-long-flip",
    concept: "Long careers, flipped",
    hook: "Same longevity cut with years vertical and people across.",
    tags: ["Longevity", "Flip"],
    spec: {
      activeConstruct: "long_careers",
      heroForm: "timeline",
      topN: 70,
      minWeight: 2,
      timelineFlip: true,
      sortBy: "year_peak",
      minTitles: 5,
      labelMode: "hubs",
      palette: "ink",
    },
  },
  {
    id: "careers-long-chord",
    concept: "Longevity as chord",
    hook: "Long-span collaborators on a circle — who kept meeting.",
    tags: ["Longevity", "Chord"],
    spec: {
      activeConstruct: "long_careers",
      heroForm: "chord",
      topN: 90,
      minWeight: 2,
      colorMode: "degree",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "dusk",
    },
  },
  {
    id: "careers-bridges",
    concept: "Genre bridge builders",
    hook: "Careers spanning two+ genres — the connectors in the loom.",
    tags: ["Bridges", "Bundle"],
    spec: {
      activeConstruct: "genre_bridge",
      heroForm: "bundle",
      topN: 100,
      minWeight: 2,
      minTitles: 4,
      sortBy: "title_count",
      colorMode: "degree",
      labelMode: "hubs",
      palette: "loom",
      statMarks: marks("bridge_outliers", "top5_degree"),
    },
  },
  {
    id: "careers-bridges-chord",
    concept: "Bridges as chord",
    hook: "Multi-genre people co-appearance — who spans the map together.",
    tags: ["Bridges", "Chord"],
    spec: {
      activeConstruct: "genre_bridge",
      heroForm: "chord",
      topN: 100,
      minWeight: 2,
      minTitles: 3,
      colorMode: "degree",
      sortBy: "title_count",
      palette: "dusk",
      labelMode: "hubs",
    },
  },
  {
    id: "careers-bridges-time",
    concept: "Bridge careers over time",
    hook: "Multi-genre careers as lanes — when the crossing happens.",
    tags: ["Bridges", "Timeline"],
    spec: {
      activeConstruct: "genre_bridge",
      heroForm: "timeline",
      topN: 90,
      minWeight: 2,
      minTitles: 4,
      sortBy: "year_peak",
      palette: "ink",
      statMarks: marks("genre_drift", "median_peak"),
    },
  },
  {
    id: "careers-one-role",
    concept: "One-role wonders",
    hook: "≥90% one genre, stratified by prominence — specialists clustering by lane.",
    tags: ["One-role", "Chord"],
    spec: {
      activeConstruct: "one_role",
      heroForm: "chord",
      topN: 40,
      minWeight: 1,
      colorMode: "degree",
      sortBy: "prominence",
      labelMode: "hubs",
      palette: "loom",
      statMarks: marks("genre_entropy", "community_cuts"),
    },
  },
  {
    id: "careers-one-role-time",
    concept: "Specialists over time",
    hook: "One-genre careers as a timeline — concentration across eras.",
    tags: ["One-role", "Timeline"],
    spec: {
      activeConstruct: "one_role",
      heroForm: "timeline",
      topN: 40,
      minWeight: 1,
      sortBy: "year_peak",
      colorMode: "degree",
      palette: "dusk",
    },
  },
  {
    id: "careers-one-role-bundle",
    concept: "Specialist bundles",
    hook: "Genre-concentrated careers edge-bundled by affinity.",
    tags: ["One-role", "Bundle"],
    spec: {
      activeConstruct: "one_role",
      heroForm: "bundle",
      topN: 40,
      minWeight: 1,
      colorMode: "degree",
      sortBy: "prominence",
      labelMode: "none",
      palette: "ink",
    },
  },
  {
    id: "careers-bechdel",
    concept: "The Bechdel web",
    hook: "Cast across films that pass the Bechdel test (rating = 3).",
    tags: ["Bechdel", "Chord"],
    spec: {
      activeConstruct: "bechdel",
      heroForm: "chord",
      topN: 100,
      minWeight: 2,
      colorMode: "gender",
      sortBy: "strength",
      palette: "loom",
      labelMode: "hubs",
      statMarks: marks("assortativity", "top5_degree"),
    },
  },
  {
    id: "careers-bechdel-time",
    concept: "Bechdel over time",
    hook: "Pass-film collaborations as career lanes.",
    tags: ["Bechdel", "Timeline"],
    spec: {
      activeConstruct: "bechdel",
      heroForm: "timeline",
      topN: 90,
      minWeight: 2,
      minTitles: 2,
      sortBy: "year_peak",
      colorMode: "gender",
      palette: "dusk",
    },
  },
  {
    id: "careers-bechdel-women",
    concept: "Bechdel · women",
    hook: "Female-coded cast on pass films — gender-colored hubs.",
    tags: ["Bechdel", "Female"],
    spec: {
      activeConstruct: "bechdel",
      heroForm: "chord",
      topN: 90,
      minWeight: 2,
      genderFilter: "female",
      colorMode: "gender",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "loom",
    },
  },
  {
    id: "careers-scatter",
    concept: "Bridge strength cloud",
    hook: "Genre-bridge cast as strength × prominence — connectors in metric space.",
    tags: ["Scatter", "Bridges"],
    spec: {
      activeConstruct: "genre_bridge",
      heroForm: "scatter",
      topN: 160,
      minWeight: 2,
      minTitles: 3,
      sortBy: "prominence",
      palette: "ink",
    },
  },
];

/** New lenses — repertory, reunions, muses, child stars, etc. */
const NEW_LENSES: StoryPreset[] = [
  {
    id: "lens-repertory",
    concept: "Repertory companies",
    hook: "Tight troupes — people with ≥3 partners who share ≥3 titles each.",
    tags: ["Repertory", "Chord"],
    spec: {
      activeConstruct: "repertory",
      heroForm: "chord",
      topN: 90,
      minWeight: 3,
      colorMode: "degree",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "loom",
      statMarks: marks("loyalty_pair", "densest_pair", "community_cuts"),
    },
  },
  {
    id: "lens-repertory-time",
    concept: "Troupes over time",
    hook: "The same repertory cast as career lanes — when the company held.",
    tags: ["Repertory", "Timeline"],
    spec: {
      activeConstruct: "repertory",
      heroForm: "timeline",
      topN: 80,
      minWeight: 3,
      sortBy: "year_peak",
      palette: "dusk",
      labelMode: "hubs",
    },
  },
  {
    id: "lens-child-stars",
    concept: "Child stars",
    hook: "Debuted before 12 — what the voice-room next chapter looks like.",
    tags: ["Child stars", "Timeline"],
    spec: {
      activeConstruct: "child_stars",
      heroForm: "timeline",
      topN: 90,
      minWeight: 2,
      sortBy: "year_peak",
      colorMode: "gender",
      palette: "dusk",
      labelMode: "hubs",
      statMarks: marks("retention_meter", "median_peak"),
    },
  },
  {
    id: "lens-child-chord",
    concept: "Child-star web",
    hook: "Who grew up on screen together — co-appearance among early debuts.",
    tags: ["Child stars", "Chord"],
    spec: {
      activeConstruct: "child_stars",
      heroForm: "chord",
      topN: 80,
      minWeight: 2,
      colorMode: "gender",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "loom",
    },
  },
  {
    id: "lens-same-character",
    concept: "Same character club",
    hook: "Batmans, Bonds, Wardens — roles worn by many faces (Kenny’s SpongeBob lane).",
    tags: ["Characters", "Bundle"],
    spec: {
      activeConstruct: "same_character",
      heroForm: "bundle",
      topN: 110,
      minWeight: 1,
      minTitles: 1,
      colorMode: "degree",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "dusk",
      statMarks: marks("community_cuts", "top5_degree"),
    },
  },
  {
    id: "lens-same-char-chord",
    concept: "Character inheritance",
    hook: "Shared character names as a circle — legacy casting as a weave.",
    tags: ["Characters", "Chord"],
    spec: {
      activeConstruct: "same_character",
      heroForm: "chord",
      topN: 90,
      minWeight: 1,
      colorMode: "degree",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "ink",
    },
  },
  {
    id: "lens-muses",
    concept: "Director's muses",
    hook: "Actors with ≥4 titles under one director — loyalty as a chord.",
    tags: ["Muses", "Chord"],
    spec: {
      activeConstruct: "director_muses",
      heroForm: "chord",
      topN: 90,
      minWeight: 2,
      colorMode: "degree",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "loom",
      statMarks: marks("loyalty_pair", "densest_pair"),
    },
  },
  {
    id: "lens-muses-timeline",
    concept: "Muses over time",
    hook: "Director–actor loyalty lanes across decades.",
    tags: ["Muses", "Timeline"],
    spec: {
      activeConstruct: "director_muses",
      heroForm: "timeline",
      topN: 90,
      minWeight: 2,
      sortBy: "year_peak",
      palette: "dusk",
      labelMode: "hubs",
      statMarks: marks("longest_collab", "median_peak"),
    },
  },
  {
    id: "lens-reunions",
    concept: "The reunion map",
    hook: "Cleese, Palin, MacNeille — pairs who vanished 20+ years, then met again.",
    tags: ["Reunions", "Timeline"],
    spec: {
      activeConstruct: "reunions",
      heroForm: "timeline",
      topN: 90,
      minWeight: 1,
      sortBy: "year_peak",
      palette: "ink",
      labelMode: "hubs",
      statMarks: marks("reunion_edges", "gap_spikes", "median_peak"),
    },
  },
  {
    id: "lens-reunions-chord",
    concept: "Reunions as chord",
    hook: "The same 20-year gaps, read as a circle of long-dormant ties.",
    tags: ["Reunions", "Chord"],
    spec: {
      activeConstruct: "reunions",
      heroForm: "chord",
      topN: 80,
      minWeight: 1,
      colorMode: "degree",
      sortBy: "strength",
      palette: "loom",
      labelMode: "hubs",
      statMarks: marks("reunion_edges", "densest_pair"),
    },
  },
  {
    id: "lens-genre-drift",
    concept: "Genre drift",
    hook: "Jackson, Hamill, Radcliffe — early vs late genres that barely overlap.",
    tags: ["Drift", "Timeline"],
    spec: {
      activeConstruct: "genre_drift",
      heroForm: "timeline",
      topN: 90,
      minWeight: 2,
      sortBy: "year_peak",
      colorMode: "degree",
      palette: "dusk",
      labelMode: "hubs",
      statMarks: marks("genre_drift", "median_peak", "mode_decade"),
    },
  },
  {
    id: "lens-comeback",
    concept: "Comeback trail",
    hook: "Eight-year (or longer) hiatus, then five or more credits after.",
    tags: ["Comeback", "Timeline"],
    spec: {
      activeConstruct: "comeback",
      heroForm: "timeline",
      topN: 100,
      minWeight: 1,
      sortBy: "year_peak",
      palette: "ink",
      labelMode: "hubs",
      statMarks: marks("gap_spikes", "retention_meter"),
    },
  },
  {
    id: "lens-blockbuster",
    concept: "Blockbuster ensemble",
    hook: "Careers mostly spent in top-decile-vote titles — Jackson to Diesel.",
    tags: ["Blockbuster", "Chord"],
    spec: {
      activeConstruct: "blockbuster",
      heroForm: "chord",
      topN: 90,
      minWeight: 2,
      colorMode: "degree",
      sortBy: "prominence",
      labelMode: "hubs",
      palette: "loom",
      statMarks: marks("votes_centroid", "top5_prominence", "densest_pair"),
    },
  },
  {
    id: "lens-b-movie",
    concept: "B-movie loyalists",
    hook: "The inverse loom — careers loyal to below-median-vote titles.",
    tags: ["B-movie", "Chord"],
    spec: {
      activeConstruct: "b_movie",
      heroForm: "chord",
      topN: 90,
      minWeight: 2,
      colorMode: "degree",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "ink",
    },
  },
  {
    id: "lens-national",
    concept: "National cinema bridges",
    hook: "Actors credited across two or more production regions.",
    tags: ["Regions", "Bundle"],
    spec: {
      activeConstruct: "national_bridges",
      heroForm: "bundle",
      topN: 100,
      minWeight: 2,
      colorMode: "degree",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "dusk",
      statMarks: marks("bridge_outliers", "community_cuts"),
    },
  },
  {
    id: "lens-hyphenates",
    concept: "The hyphenates",
    hook: "Cleese, Rogen, Stiller, Wiig — actor-directors and actor-writers.",
    tags: ["Hyphenates", "Chord"],
    spec: {
      activeConstruct: "hyphenates",
      heroForm: "chord",
      topN: 90,
      minWeight: 2,
      colorMode: "gender",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "loom",
      statMarks: marks("top5_degree", "densest_pair"),
    },
  },
  {
    id: "lens-hyphenates-time",
    concept: "Hyphenate careers",
    hook: "Two-hat careers as lanes — when directing and acting overlap.",
    tags: ["Hyphenates", "Timeline"],
    spec: {
      activeConstruct: "hyphenates",
      heroForm: "timeline",
      topN: 80,
      minWeight: 2,
      sortBy: "year_peak",
      colorMode: "gender",
      palette: "dusk",
      labelMode: "hubs",
    },
  },
];

const ARCHETYPES: StoryPreset[] = [
  {
    id: "arch-franchise",
    concept: "Franchise nomads",
    hook: "People who hop across three or more series / IP groups.",
    tags: ["Franchise", "Bundle"],
    spec: {
      activeConstruct: "franchise_nomads",
      heroForm: "bundle",
      topN: 100,
      minWeight: 2,
      colorMode: "degree",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "dusk",
      statMarks: marks("community_cuts", "top5_degree"),
    },
  },
  {
    id: "arch-franchise-chord",
    concept: "Franchise as chord",
    hook: "IP hoppers on a circle — who keeps meeting across franchises.",
    tags: ["Franchise", "Chord"],
    spec: {
      activeConstruct: "franchise_nomads",
      heroForm: "chord",
      topN: 80,
      minWeight: 3,
      colorMode: "degree",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "ink",
    },
  },
  {
    id: "arch-doc-selves",
    concept: "Documentary selves",
    hook: "The talk-show / documentary ecosystem of people credited as Self.",
    tags: ["Documentary", "Chord"],
    spec: {
      activeConstruct: "documentary_selves",
      heroForm: "chord",
      topN: 90,
      minWeight: 2,
      colorMode: "degree",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "loom",
    },
  },
  {
    id: "arch-typecast",
    concept: "Typecast index",
    hook: "Welker, Messick, Hayashibara — careers defined by a sticky character name.",
    tags: ["Typecast", "Chord"],
    spec: {
      activeConstruct: "typecast",
      heroForm: "chord",
      topN: 90,
      minWeight: 2,
      colorMode: "degree",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "ink",
      statMarks: marks("densest_pair", "top5_degree"),
    },
  },
  {
    id: "arch-typecast-time",
    concept: "Typecast over time",
    hook: "Repeated-character careers as lanes across decades.",
    tags: ["Typecast", "Timeline"],
    spec: {
      activeConstruct: "typecast",
      heroForm: "timeline",
      topN: 80,
      minWeight: 2,
      sortBy: "year_peak",
      palette: "dusk",
      labelMode: "hubs",
    },
  },
  {
    id: "arch-silent-sound",
    concept: "Silent → sound survivors",
    hook: "McKee, Hatton, London — careers that straddled 1927.",
    tags: ["Silent era", "Timeline"],
    spec: {
      activeConstruct: "silent_sound",
      heroForm: "timeline",
      topN: 80,
      minWeight: 1,
      sortBy: "year_peak",
      palette: "ink",
      labelMode: "hubs",
      statMarks: marks("median_peak", "mode_decade", "gap_spikes"),
    },
  },
  {
    id: "arch-silent-chord",
    concept: "Talkie transition web",
    hook: "Silent→sound survivors as a co-appearance chord.",
    tags: ["Silent era", "Chord"],
    spec: {
      activeConstruct: "silent_sound",
      heroForm: "chord",
      topN: 80,
      minWeight: 1,
      colorMode: "degree",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "loom",
    },
  },
  {
    id: "arch-horror-blood",
    concept: "Horror bloodlines",
    hook: "Dense horror co-appearance across genders — the royal court of screams.",
    tags: ["Horror", "Chord"],
    spec: {
      activeConstruct: "horror_bloodlines",
      heroForm: "chord",
      topN: 90,
      minWeight: 3,
      colorMode: "gender",
      sortBy: "strength",
      palette: "ink",
      labelMode: "hubs",
    },
  },
  {
    id: "arch-dynasties",
    concept: "Acting dynasties",
    hook: "Family trees (when Wikidata is warm) woven with co-appearance.",
    tags: ["Family", "Chord"],
    spec: {
      activeConstruct: "acting_dynasties",
      heroForm: "chord",
      topN: 90,
      minWeight: 1,
      colorMode: "gender",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "dusk",
      statMarks: marks("featured_path", "densest_pair"),
    },
  },
  {
    id: "arch-athletes",
    concept: "Athletes to actors",
    hook: "Wrestlers, martial artists, and athletes who crossed onto the screen.",
    tags: ["Athletes", "Chord"],
    spec: {
      activeConstruct: "athletes_actors",
      heroForm: "chord",
      topN: 90,
      minWeight: 2,
      colorMode: "gender",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "loom",
    },
  },
  {
    id: "arch-drama-schools",
    concept: "Drama school webs",
    hook: "RADA / Juilliard / stage-school clusters — classmates who kept meeting.",
    tags: ["Schools", "Bundle"],
    spec: {
      activeConstruct: "drama_schools",
      heroForm: "bundle",
      topN: 100,
      minWeight: 2,
      colorMode: "degree",
      sortBy: "strength",
      labelMode: "hubs",
      palette: "ink",
      statMarks: marks("community_cuts", "loyalty_pair"),
    },
  },
  {
    id: "arch-awards",
    concept: "Award season cohorts",
    hook: "Award-linked careers woven by the titles they actually share.",
    tags: ["Awards", "Chord"],
    spec: {
      activeConstruct: "award_cohorts",
      heroForm: "chord",
      topN: 90,
      minWeight: 2,
      colorMode: "degree",
      sortBy: "prominence",
      labelMode: "hubs",
      palette: "loom",
      statMarks: marks("top5_prominence", "votes_centroid", "densest_pair"),
    },
  },
  {
    id: "arch-awards-scatter",
    concept: "Award cohort cloud",
    hook: "Award-linked cast as strength × prominence — fame vs collaboration weight.",
    tags: ["Scatter", "Awards"],
    spec: {
      activeConstruct: "award_cohorts",
      heroForm: "scatter",
      topN: 160,
      minWeight: 2,
      sortBy: "prominence",
      palette: "dusk",
    },
  },
  {
    id: "arch-blockbuster-time",
    concept: "Blockbuster careers",
    hook: "Top-decile-vote careers as lanes — when the ensemble years land.",
    tags: ["Blockbuster", "Timeline"],
    spec: {
      activeConstruct: "blockbuster",
      heroForm: "timeline",
      topN: 90,
      minWeight: 2,
      sortBy: "year_peak",
      colorMode: "degree",
      palette: "loom",
      labelMode: "hubs",
      statMarks: marks("votes_centroid", "median_peak"),
    },
  },
];

export const GALLERY_COLLECTIONS: GalleryCollection[] = [
  {
    id: "look-cool",
    label: "Just look cool",
    blurb: "Form, density, and palette first — weaves picked because they read as objects.",
    stories: LOOK_COOL,
  },
  {
    id: "horror",
    label: "Horror webs",
    blurb: "Scream queens, bloodlines, gendered horror casts, and comedy × horror crossovers.",
    stories: HORROR,
  },
  {
    id: "voice",
    label: "Voice & cartoons",
    blurb: "Animation voice rooms, dubbing multiverse, and voice↔face careers.",
    stories: VOICE,
  },
  {
    id: "careers",
    label: "Careers & bridges",
    blurb: "Longevity, multi-genre connectors, one-role specialists, and the Bechdel web.",
    stories: CAREERS,
  },
  {
    id: "new-lenses",
    label: "New lenses",
    blurb: "Repertory troupes, muses, reunions, child stars, hyphenates, and character clubs.",
    stories: NEW_LENSES,
  },
  {
    id: "archetypes",
    label: "Archetypes & eras",
    blurb: "Typecasting, franchise hoppers, silent-era survivors, awards, and family trees.",
    stories: ARCHETYPES,
  },
];

/** Flat list (all tabs) — useful for search / deep links. */
export const GALLERY_STORIES: StoryPreset[] = GALLERY_COLLECTIONS.flatMap((c) => c.stories);

export function collectionById(id: string | null | undefined): GalleryCollection {
  return GALLERY_COLLECTIONS.find((c) => c.id === id) ?? GALLERY_COLLECTIONS[0];
}

export function resolveStorySpec(story: StoryPreset): PosterSpec {
  return { ...DEFAULT_SPEC, ...story.spec };
}

export function storyToHref(story: StoryPreset, baseUrl = "/"): string {
  const spec = resolveStorySpec(story);
  const qs = specToSearchParams(spec);
  qs.set("view", "atelier");
  const base = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;
  return `${base}?${qs.toString()}`;
}

export function atelierHref(baseUrl = "/"): string {
  const qs = specToSearchParams(DEFAULT_SPEC);
  qs.set("view", "atelier");
  const base = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;
  return `${base}?${qs.toString()}`;
}

export function homeHref(baseUrl = "/", tab?: string): string {
  const base = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;
  const qs = new URLSearchParams({ view: "home" });
  if (tab && tab !== GALLERY_COLLECTIONS[0].id) qs.set("tab", tab);
  return `${base}?${qs.toString()}`;
}

const ATELIER_HINTS = [
  "construct",
  "hero",
  "topN",
  "minWeight",
  "minTitles",
  "gender",
  "yearFrom",
  "yearTo",
  "search",
  "flip",
  "palette",
  "size",
] as const;

/** Decide landing surface from the current query string. */
export function viewFromSearchParams(
  params: URLSearchParams,
): "home" | "atelier" | "methodology" {
  if (params.has("print")) return "atelier";
  const view = params.get("view");
  if (view === "home" || view === "gallery") return "home";
  if (view === "methodology") return "methodology";
  if (view === "atelier") return "atelier";
  if (ATELIER_HINTS.some((k) => params.has(k))) return "atelier";
  return "home";
}
